# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 46.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.models.gene_location import GeneLocation

class TestGeneLocation(unittest.TestCase):
    """GeneLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneLocation:
        """Test GeneLocation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneLocation`
        """
        model = GeneLocation()
        if include_optional:
            return GeneLocation(
                start = 0,
                end = 0,
                chromosome = 'chrC',
                assembly = 'GRCh38'
            )
        else:
            return GeneLocation(
                start = 0,
                end = 0,
                chromosome = 'chrC',
                assembly = 'GRCh38',
        )
        """

    def testGeneLocation(self):
        """Test GeneLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
