# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 46.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.models.locus import Locus

class TestLocus(unittest.TestCase):
    """Locus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Locus:
        """Test Locus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Locus`
        """
        model = Locus()
        if include_optional:
            return Locus(
                start = 1,
                end = 1,
                chromosome = 'chrH',
                assembly = 'GRCh38'
            )
        else:
            return Locus(
                start = 1,
                end = 1,
                chromosome = 'chrH',
                assembly = 'GRCh38',
        )
        """

    def testLocus(self):
        """Test Locus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
